name: CD practice

on:
  release:
    types: [created]

jobs:
  publish:
    name: Build and publish the package
    runs-on: 'ubuntu-latest'
    steps:
      - name: Setup Ubuntu & Node environment
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Get package's version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Check if versions of GitHub Release Tag and package.json are the same
        run: |
          if [[ "${{ github.ref_name }}" != "${{ format('v{0}', steps.package-version.outputs.current-version) }}" ]]; then
            echo "The tag version and package.json's version should be the same!"
            exit 1
          fi
          exit 0
        shell: bash
      - name: Install Node dependencies
        run: npm ci
      - name: Build node package
        run: npm run build
      - name: Publish the package to NPM publicly
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
