name: CI practice

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Build
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
